[package]
name = "logo-web"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
logo-renderer = {path = '../logo-renderer'}
wasm-bindgen = { workspace = true }
js-sys = "0.3.64"
