[package]
name = "logo-renderer"
version.workspace = true
edition.workspace = true

[dependencies]
logo-runtime = {path = '../logo-runtime'}
raqote = { version = "0.8.2", default-features = false, features = ["png"] }
wasm-bindgen = { workspace = true }
